version: '3.8'

services:
  bff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aki-bff
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - aki-network

networks:
  aki-network:
    driver: bridge
